const recoveryHash=new URLSearchParams(location.hash.slice(1));
const recoveryToken=recoveryHash.get('access_token');
const recoveryType=recoveryHash.get('type');
import {config} from './config.js';
import {configured,request,signIn,signOut,currentSession,node} from './api.js';
import {compress,checkVideo} from './media.js';
const el=id=>document.getElementById(id);let oldRecord=null,dirty=false;
const initialType=new URLSearchParams(location.search).get('section')==='testimonials'?'welcome':'update';
function setType(){const testimonial=el('post-type').value==='welcome';el('testimonial-hint').hidden=!testimonial;el('media').accept=testimonial?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,video/mp4,video/webm';}
el('post-type').onchange=setType;el('post-type').value=initialType;setType();
function status(message,error=false){el('status').textContent=message;el('status').classList.toggle('error',error);}
function reset(){el('editor').reset();el('post-type').value=initialType;setType();el('record-id').value='';el('existing-media').textContent='';oldRecord=null;el('video-fields').hidden=true;el('transcript').required=false;dirty=false;}
function videoSelected(){return el('media').files[0]?.type.startsWith('video/')||(!el('media').files[0]&&/\.(mp4|webm)$/.test(oldRecord?.media_path||''));}
el('media').onchange=()=>{el('video-fields').hidden=!videoSelected();el('transcript').required=!!videoSelected();};
el('editor').oninput=()=>{dirty=true;};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
status(configured?'Log in to post photos and short videos.':'Admin login is awaiting secure account setup. Posting is disabled until connected.');
if(configured&&recoveryToken&&recoveryType==='recovery'){
  el('login-panel').hidden=true;el('reset-panel').hidden=false;status('Choose a new password.');
  el('reset-form').onsubmit=async e=>{e.preventDefault();const password=el('new-password').value;if(password!==el('confirm-password').value){status('The passwords do not match.',true);return;}el('reset-button').disabled=true;try{const res=await fetch(config.supabaseUrl+'/auth/v1/user',{method:'PUT',headers:{apikey:config.publishableKey,Authorization:'Bearer '+recoveryToken,'Content-Type':'application/json'},body:JSON.stringify({password})});if(!res.ok)throw new Error('This reset link is expired. Request a new one.');history.replaceState({},'',location.pathname);el('reset-panel').hidden=true;el('login-panel').hidden=false;el('email').value='';status('Password updated. Log in with your new password.');}catch(err){status(err.message,true);}finally{el('reset-button').disabled=false;}};
}
el('login-button').disabled=!configured;
el('login').onsubmit=async e=>{e.preventDefault();el('login-button').disabled=true;try{await signIn(el('email').value.trim(),el('password').value);el('password').value='';el('login-panel').hidden=true;el('editor-panel').hidden=false;document.querySelector('h1').textContent='Post an update';await load();status('Logged in. Choose a photo or short video to publish.');}catch(e){status(e.message,true);}finally{el('login-button').disabled=!configured;}};
el('logout').onclick=async()=>{if(dirty&&!confirm('Leave this unsaved post?'))return;try{await signOut();}catch{}reset();el('editor-panel').hidden=true;el('login-panel').hidden=false;el('records').replaceChildren();document.querySelector('h1').textContent='Admin login';status('Logged out.');};
el('new').onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;reset();el('title').focus();};
async function upload(file){const photo=['image/jpeg','image/png','image/webp'].includes(file.type);if(!photo&&!['video/mp4','video/webm'].includes(file.type))throw new Error('Choose a JPEG, PNG, WebP, MP4, or WebM file.');if(!photo)await checkVideo(file);const blob=photo?await compress(file):file;const ext=photo?'webp':file.type==='video/mp4'?'mp4':'webm';const path=currentSession().user.id+'/'+crypto.randomUUID()+'.'+ext;await request('/storage/v1/object/project-media/'+path,{method:'POST',body:blob,headers:{'Content-Type':blob.type,'x-upsert':'false','cache-control':'600'}});return path;}
el('editor').onsubmit=async e=>{e.preventDefault();if(!currentSession()){status('Log in before publishing.',true);return;}let uploaded=null,saved=false;el('publish').disabled=true;try{const file=el('media').files[0];if(!file&&!oldRecord?.media_path)throw new Error('Choose a photo or video.');if(el('post-type').value==='welcome'&&!videoSelected())throw new Error('Choose a video for a testimonial.');if(videoSelected()&&!el('transcript').value.trim())throw new Error('Add the video description and spoken words.');const title=el('title').value.trim(),caption=el('caption').value.trim();if(!title||!caption)throw new Error('Add a title and caption.');status('Preparing your post…');if(file)uploaded=await upload(file);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Honolulu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const row={kind:el('post-type').value,title,body:caption,caption:'',alt_text:caption,transcript:videoSelected()?el('transcript').value.trim():'',media_path:uploaded||oldRecord.media_path,work_date:oldRecord?.work_date||null,published:true,approved:true};
const id=el('record-id').value;await request('/rest/v1/entries'+(id?'?id=eq.'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',body:row});saved=true;reset();status('Published. Your post is now on the website.');try{await load();}catch{status('Published successfully. Reload to refresh the post list.');}
}catch(e){if(uploaded&&!saved){try{await request('/storage/v1/object/project-media',{method:'DELETE',body:{prefixes:[uploaded]}});}catch{}}status(e.message,true);}finally{el('publish').disabled=false;}};
async function load(){const records=await request('/rest/v1/entries?select=*&kind=in.(update,welcome)&order=created_at.desc');el('records').replaceChildren();if(!records.length)el('records').append(node('p','No posts yet.'));for(const r of records){const row=node('article',undefined,'admin-record');const text=node('div');text.append(node('strong',r.title),node('small',(r.kind==='welcome'?'Testimonial · ':'Progress blog · ')+(r.published?'Published':'Hidden')));const actions=node('div',undefined,'toolbar');const edit=node('button','Edit','button secondary');edit.onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;reset();oldRecord=r;el('post-type').value=r.kind;setType();el('record-id').value=r.id;el('title').value=r.title;el('caption').value=r.body;el('transcript').value=r.transcript;el('existing-media').textContent='Photo/video saved. Choose a new file only to replace it.';el('media').onchange();el('title').focus();};actions.append(edit);if(r.published){const hide=node('button','Unpublish','button secondary');hide.onclick=async()=>{try{await request('/rest/v1/entries?id=eq.'+r.id,{method:'PATCH',body:{published:false}});await load();status('Post removed from public view.');}catch(e){status(e.message,true);}};actions.append(hide);}row.append(text,actions);el('records').append(row);}}


